server:
  port: 2073

spring:
  application:
    name: zuul2073
  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:2072/eureka/ #Eureka??
zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    example2060:
      path: /example2060/**
      service-id: example2060
      #url: http://localhost:2060
    auth2074:
      path: /auth2074/**
      service-id: auth2074
    file2075:
      path: /file2075/**
      service-id: file2075
    log2076:
      path: /log2076/**
      service-id: log2076


#http://localhost:1080/sscloud/test
#http://localhost:1073/twin-sign-1080/sscloud/test